config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  
  resources :courses do 
    resources :assignments
    resources :enrollments
  end 
  resources :assignments, except: :index do 
    resources :submissions
  end 
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#welcome'
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    
  end 
end

app/models/assignment.rb
class Assignment < ApplicationRecord

    belongs_to :course 
    has_many :submissions
    # has_many :assignments_as_teacher
    accepts_nested_attributes_for :course, reject_if: :all_blank

    validates :assignment_name, :presence => true, uniqueness: {scope: [:course_id ]} 
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    
    before_action :authenticate_user!
    

    def show
        @assignment = Assignment.find_by(id: params[:id])
    end
    
    def index
        
       if params[:course_id]
            set_course
            @assignments = @course.assignments
            @teacher = @course.teacher == current_user
       else 
            @assignments = Assignment.all
       end 

    end

    def new
        @assignment = Assignment.new
        @assignment = current_user.assignments_as_teacher.new(course_id: params[:course_id])
    # @assignment.courses.build

    end

    def create

        @assignment = Assignment.create(assignment_params)
        
        if @assignment.save
            flash[:success] = "Your Assignment has been Created!!"
            redirect_to course_assignments_path(@assignment.course)
        else 
            flash[:error] = "Error !!"
            render  new
        end 


    end

    private

    def assignment_params
    params.require(:assignment).permit(:assignment_name, :description, :q_1, :q_2, :q_3, :course_id)
    # :course_attributes => [:name]
    end

    def set_course
        @course = Course.find(params[:course_id])
    end 
end
  
    

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for (@assignment) do |f| %>
 
    <%= f.hidden_field :course_id %>

    <%= f.label :assignment_name %>
    <%= f.text_field :assignment_name %><br>
    <br>
    <%= f.label :description %><br>
    <%= f.text_area :description  %><br>
    <br>
    <%= f.label :question_1 %><br>
    <%= f.text_area :q_1  %><br>
    <br>
    <%= f.label :question_2 %><br>
    <%= f.text_area  :q_2  %><br>
    <br>
    <%= f.label :question_3 %><br>
    <%= f.text_area :q_3  %><br>
    <br>

    <%= f.submit %>
<% end %>

app/views/assignments/index.html.erb
<center><h1> Welcome to Assignment Index</h1>

<% if @teacher %>
    <%= current_user.username %> <br> Welcome Back!! <br> Would you like to Create a new assignment for this Course?<br>
    <%= link_to "Add Assignment", new_course_assignment_path(@course)%> 

<% end %>
</center>
<ul>
   
    <% @assignments.each do |assignment| %>
        <li>Name: <%= link_to assignment.assignment_name, assignment_path(assignment), class: 'btn btn-success'%> </li>

        <% if submission = assignment.submissions.by_user(current_user).first%>
            <%= link_to "Submitted Assignemnt", assignment_submission_path(assignment, submission) %> 
        <% end %>
    <% end %>
</ul>
<br>
<br>
<br>

app/views/assignments/new.html.erb
<h1><center>Create an Assignment </center></h1>
<h3><center>Only a signed in user will be able to create an assignment</center></h3>

<%= render 'form', assignment: Assignment.new %>
<br><br><br><br>

app/views/assignments/show.html.erb
<center>
    <h1> <%= @assignment.assignment_name %></h1>
    <h2><%= @assignment.description%></h2><br>

    <fieldset>
        <legend>Quetions</legend>
            <li><%= @assignment. q_1%></li>
            <li><%= @assignment. q_2%></li>
            <li><%= @assignment. q_3%></li>
    </fieldset>
    <br>
    <%=link_to 'Complete Assignment', {:controller => "submissions", :action => "new", :assignment_id => @assignment.id }%>
</center}